const sections = [
    "home",
    "arts",
    "automobiles",
    "books",
    "business",
    "fashion",
    "food",
    "health",
    "movies",
    "technology",
    "politics",

//     "insider",
//     "magazine",
//     "nyregion",
//     "obituaries",
//     "opinion",
//     "realestate",
//     "science",
//     "sports",
//     "sundayreview",
//     "theater",
//     "magazine",
//     "travel",
//     "upshot",
//     "us",
//     "world",
]

export default sections